export const DEFAULT_VALUES = {
  ELEMENT_WIDTH: 100,
  ELEMENT_HEIGHT: 40,
  TEXT_WIDTH: 200,
  FONT_SIZE: 16,
  SVG_SIZE: 32,
  CANVAS_WIDTH: 500,
  CANVAS_HEIGHT: 500,
  MIN_ELEMENT_SIZE: 10,
  MAX_ELEMENT_SIZE: 800,
} as const
