import { type PopupDesign, ELEMENT_TYPES, SVG_TYPES } from '@/types'
import { DEFAULT_VALUES } from '@/lib/constants'

export const defaultDesign: PopupDesign = {
  id: 'default',
  name: 'Default Popup',
  backgroundColor: '#E07A5F',
  width: DEFAULT_VALUES.CANVAS_WIDTH,
  height: DEFAULT_VALUES.CANVAS_HEIGHT,
  createdAt: new Date().toISOString(),
  elements: [
    {
      id: 'star1',
      type: ELEMENT_TYPES.SVG,
      content: SVG_TYPES.STAR,
      svgType: SVG_TYPES.STAR,
      svgSize: DEFAULT_VALUES.SVG_SIZE,
      x: 190,
      y: 60,
      color: '#FBFF37',
    },
    {
      id: 'star2',
      type: ELEMENT_TYPES.SVG,
      content: SVG_TYPES.STAR,
      svgType: SVG_TYPES.STAR,
      svgSize: 40,
      x: 232,
      y: 38,
      color: '#FBFF37',
    },
    {
      id: 'star3',
      type: ELEMENT_TYPES.SVG,
      content: SVG_TYPES.STAR,
      svgType: SVG_TYPES.STAR,
      svgSize: DEFAULT_VALUES.SVG_SIZE,
      x: 278,
      y: 60,
      color: '#FBFF37',
    },
    {
      id: 'title',
      type: ELEMENT_TYPES.TEXT,
      content: 'All the text and elements in this popup should be editable and draggable',
      x: 100,
      y: 130,
      width: 300,
      fontSize: 24,
      color: '#FFFFFF',
    },
    {
      id: 'email',
      type: ELEMENT_TYPES.INPUT,
      content: 'E-mail',
      x: 100,
      y: 240,
      width: 300,
      height: 50,
      backgroundColor: '#FFFFFF',
    },
    {
      id: 'button',
      type: ELEMENT_TYPES.BUTTON,
      content: 'SIGNUP NOW',
      x: 100,
      y: 310,
      width: 300,
      height: 50,
      backgroundColor: '#2D3748',
      color: '#FFFFFF',
    },
    {
      id: 'subtitle',
      type: ELEMENT_TYPES.TEXT,
      content: 'No credit card required. No Surprises',
      x: 100,
      y: 380,
      width: 300,
      fontSize: 14,
      color: '#FFFFFF',
    },
  ],
}
